#!/usr/bin/env bash

if ! test -d .git; then
    echo "Execute scripts/install-git-hooks in the top-level directory."
    exit 1
fi

ln -sf ../../scripts/pre-commit.hook .git/hooks/pre-commit || exit 1
chmod +x .git/hooks/pre-commit

touch .git/hooks/applied || exit 1

echo
echo "Git hooks are installed successfully."

